/* Generated by re2c 0.13.5 on Thu Oct 13 18:31:51 2011 */
#line 1 "forte_lexer.re"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "forte_lexer.h"
#include "forte_parser.h"

@implementation TemplateScanner
@synthesize cursor = cursor_, marker = marker_, limit = limit_;
@synthesize token = token_, token_name = token_name_, state = state_, line = line_;

// Initializer.
- (id)init:(NSString *)text {
    self = [super init];
    if (self != nil) {
        int length = [text lengthOfBytesUsingEncoding:NSUTF8StringEncoding] + 1;	
        char *str = (char *)malloc(sizeof(char) * length);
        [text getCString:str maxLength:length encoding:NSUTF8StringEncoding];

        cursor_ = str;
        limit_ = str;
        marker_ = 0;
        YYSETSTATE(STATE(RAW));
        line_ = 1;
    }
    return self;
}

// Sets current token name.
- (void)setTokenName:(NSString *)name {
	token_name_ = name;
}

// Gets next token name. Returns nil if next token does not exist.
- (NSString *)next {
	return yylex() != 0 ? token_name_ : nil;
}

@end


static char* get_text() { 
  int len = scanner.cursor - scanner.token;
  char *val = (char *)malloc(sizeof(char) * (len + 1));
  memcpy(val, scanner.token, len);
  val[len] = '\0';
  return val;
}

static void inc_line_number() {
    char *str = get_text();
    int i = 0, line = 0;
    for (i = 0; i < strlen(str); i++)
        if (str[i] == '\n') line++;
    scanner.line += line;
}

static inline int t_echo() {
	[scanner setTokenName:@"T_ECHO"];
	return T_ECHO;
}

static inline int t_raw() {
	[scanner setTokenName:@"T_RAW"];
	NSString *text = [NSString stringWithCString:get_text()
										encoding:NSUTF8StringEncoding];
    inc_line_number();
	yylval.token = [Token tokenWithSymbol:T_RAW lineNumber:scanner.line value:text];
	return T_RAW;
}

static inline int t_extends() {
	[scanner setTokenName:@"T_EXTENDS"];
	yylval.token = [Token tokenWithSymbol:T_EXTENDS lineNumber:scanner.line value:@"extends"];
	return T_EXTENDS;
}

static inline int t_block() {
	[scanner setTokenName:@"T_BLOCK"];
	yylval.token = [Token tokenWithSymbol:T_BLOCK lineNumber:scanner.line value:@"block"];
	return T_BLOCK;
}

static inline int t_endblock() {
	[scanner setTokenName:@"T_ENDBLOCK"];
	yylval.token = [Token tokenWithSymbol:T_ENDBLOCK lineNumber:scanner.line value:@"endblock"];
	return T_ENDBLOCK;
}

static inline int t_parent() {
	[scanner setTokenName:@"T_PARENT"];
	yylval.token = [Token tokenWithSymbol:T_PARENT lineNumber:scanner.line value:@"parent"];
	return T_PARENT;
}

static inline int t_include() {
	[scanner setTokenName:@"T_INCLUDE"];
	yylval.token = [Token tokenWithSymbol:T_INCLUDE lineNumber:scanner.line value:@"include"];
	return T_INCLUDE;
}

static inline int t_and() {
    [scanner setTokenName:@"T_AND"];
    yylval.token = [Token tokenWithSymbol:T_AND lineNumber:scanner.line value:@"and"];
    return T_AND;
}

static inline int t_or() {
    [scanner setTokenName:@"T_OR"];
    yylval.token = [Token tokenWithSymbol:T_OR lineNumber:scanner.line value:@"or"];
    return T_OR;
}

static inline int t_not() {
    [scanner setTokenName:@"T_NOT"];
    yylval.token = [Token tokenWithSymbol:T_NOT lineNumber:scanner.line value:@"not"];
    return T_NOT;
}

static inline int t_openparen() {
    [scanner setTokenName:@"T_OPENPAREN"];
    yylval.token = [Token tokenWithSymbol:T_OPENPAREN lineNumber:scanner.line value:@"("];
    return T_OPENPAREN;
}

static inline int t_closeparen() {
    [scanner setTokenName:@"T_CLOSEPAREN"];
    yylval.token = [Token tokenWithSymbol:T_CLOSEPAREN lineNumber:scanner.line value:@")"];
    return T_CLOSEPAREN;
}

static inline int t_double_string() {
	// Remove double-quotations.
	scanner.token++;
	scanner.cursor--;

    NSString *value = [NSString stringWithCString: get_text() encoding:NSUTF8StringEncoding];
    unichar *buffer = (unichar *)malloc(sizeof(unichar) * [value length]);
    unsigned long buf_idx = 0;

    for (unsigned long idx = 0; idx < [value length]; idx++) {
        unichar ch = [value characterAtIndex:idx];
        if (ch == '\\' && idx + 1 < [value length]) {
            unichar next = [value characterAtIndex:++idx];
            if (next == 't') {
                buffer[buf_idx++] = (unichar)'\t';
            } else if (next == 'r') {
                buffer[buf_idx++] = (unichar)'\r';
            } else if (next == 'n') {
                buffer[buf_idx++] = (unichar)'\n';
            } else if (next == '\\') {
                buffer[buf_idx++] = (unichar)'\\';
            } else if (next == '"') {
                buffer[buf_idx++] = (unichar)'"';
            } else {
                // String Escape Anything.
                buffer[buf_idx++] = next;
            }
        } else {
            buffer[buf_idx++] = ch;
        }
    }
    value = [NSString stringWithCharacters:buffer length:buf_idx];
    free(buffer);

	yylval.token = [Token tokenWithSymbol:T_STRING lineNumber:scanner.line value:value];
	scanner.cursor++;

	[scanner setTokenName:@"T_STRING"];
	return T_STRING;
}

static inline int t_single_string() {
    // Remove single-quotations.
    scanner.token++;
    scanner.cursor--;

    NSString *value = [NSString stringWithCString: get_text() encoding:NSUTF8StringEncoding];
    value = [value stringByReplacingOccurrencesOfString:@"\\\\" withString:@"\\"];
    value = [value stringByReplacingOccurrencesOfString:@"\\\'" withString:@"'"];

    yylval.token = [Token tokenWithSymbol:T_STRING lineNumber:scanner.line value:value];
    scanner.cursor++;

    [scanner setTokenName:@"T_STRING"];
    return T_STRING;
}

static inline int t_equal() {
	[scanner setTokenName:@"T_EQUAL"];
	yylval.token = [Token tokenWithSymbol:T_EQUAL lineNumber:scanner.line value:@"=="];
	return T_EQUAL;
}

static inline int t_notequal() {
	[scanner setTokenName:@"T_NOTEQUAL"];
	yylval.token = [Token tokenWithSymbol:T_NOTEQUAL lineNumber:scanner.line value:@"!="];
	return T_NOTEQUAL;
}

static inline int t_if() {
	[scanner setTokenName:@"T_IF"];
	yylval.token = [Token tokenWithSymbol:T_IF lineNumber:scanner.line value:@"if"];
	return T_IF;
}

static inline int t_elseif() {
	[scanner setTokenName:@"T_ELSEIF"];
	yylval.token = [Token tokenWithSymbol:T_ELSEIF lineNumber:scanner.line value:@"elseif"];
	return T_ELSEIF;
}

static inline int t_else() {
	[scanner setTokenName:@"T_ELSE"];
	yylval.token = [Token tokenWithSymbol:T_ELSE lineNumber:scanner.line value:@"else"];
	return T_ELSE;
}

static inline int t_endif() {
	[scanner setTokenName:@"T_ENDIF"];
	yylval.token = [Token tokenWithSymbol:T_ENDIF lineNumber:scanner.line value:@"endif"];
	return T_ENDIF;
}

static inline int t_end() {
	[scanner setTokenName:@"T_END"];
	yylval.token = [Token tokenWithSymbol:T_END lineNumber:scanner.line value:@"end"];
	return T_END;
}

static inline int t_dot() {
	[scanner setTokenName:@"T_DOT"];
	yylval.token = [Token tokenWithSymbol:T_DOT lineNumber:scanner.line value:@"."];
	return T_DOT;
}

static inline int t_pipe() {
    [scanner setTokenName:@"T_PIPE"];
    yylval.token = [Token tokenWithSymbol:T_PIPE lineNumber:scanner.line value:@"|"];
    return T_PIPE;
}

static inline int t_id() {
	[scanner setTokenName:@"T_ID"];
    yylval.token = [Token tokenWithSymbol:T_ID lineNumber:scanner.line value:[NSString stringWithCString: get_text() encoding:NSUTF8StringEncoding]];
	return T_ID;
}

// TODO(nhiroki): Not implement.
/*
int yyfill(int n) {
	scanner.cursor = [text UTF8String];
	scanner.limit = [text UTF8String];
	scanner.marker = 0;
	YYSETSTATE(STATE(RAW));
			
	//while (*++scanner.cursor && n--) ;
	//*scanner.limit = scanner.cursor;
	//return n <= 0 ? 1 : 0;
}
*/

// Shows re2c debug information. |state| means lexer state number.
// |ch| means current character.
static void yydebug(int state, char ch) {
#if 0
	NSLog(@"[DEBUG] %c (yy%d)", ch, state);
	return;
#endif
}

int yylex()
{
	NSCParameterAssert(scanner.cursor != NULL);

#line 294 "forte_lexer.re"


start:
	scanner.token = scanner.cursor;


#line 285 "forte_lexer.m"
	{
		YYCTYPE yych;
		switch (YYGETSTATE()) {
		case yycCOMMENT: goto yyc_COMMENT;
		case yycECHO: goto yyc_ECHO;
		case yycRAW: goto yyc_RAW;
		case yycSTATEMENT: goto yyc_STATEMENT;
		}
/* *********************************** */
yyc_COMMENT:

		YYDEBUG(0, *YYCURSOR);
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 0x00:	goto yy4;
		case '\n':	goto yy7;
		case '\r':	goto yy6;
		case '#':	goto yy2;
		default:	goto yy5;
		}
yy2:
		YYDEBUG(2, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '}':	goto yy9;
		default:	goto yy3;
		}
yy3:
		YYDEBUG(3, *YYCURSOR);
#line 344 "forte_lexer.re"
		{ goto start; }
#line 319 "forte_lexer.m"
yy4:
		YYDEBUG(4, *YYCURSOR);
		yych = *++YYCURSOR;
		goto yy3;
yy5:
		YYDEBUG(5, *YYCURSOR);
		yych = *++YYCURSOR;
		goto yy3;
yy6:
		YYDEBUG(6, *YYCURSOR);
		yych = *++YYCURSOR;
		goto yy3;
yy7:
		YYDEBUG(7, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(8, *YYCURSOR);
#line 345 "forte_lexer.re"
		{
        scanner.line++;
        goto start;
    }
#line 341 "forte_lexer.m"
yy9:
		YYDEBUG(9, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(10, *YYCURSOR);
		YYSETSTATE(yycRAW);
#line 305 "forte_lexer.re"
		goto start;
#line 349 "forte_lexer.m"
/* *********************************** */
yyc_ECHO:
		YYDEBUG(11, *YYCURSOR);
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 0x00:	goto yy43;
		case '\t':
		case ' ':	goto yy39;
		case '!':	goto yy32;
		case '"':	goto yy27;
		case '\'':	goto yy29;
		case '(':	goto yy23;
		case ')':	goto yy25;
		case '.':	goto yy35;
		case '/':	goto yy42;
		case '=':	goto yy31;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		case 'a':	goto yy20;
		case 'b':	goto yy17;
		case 'e':	goto yy15;
		case 'i':	goto yy19;
		case 'n':	goto yy22;
		case 'o':	goto yy21;
		case 'p':	goto yy18;
		case '|':	goto yy37;
		case '}':	goto yy14;
		default:	goto yy13;
		}
yy13:
		YYDEBUG(13, *YYCURSOR);
yy14:
		YYDEBUG(14, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '}':	goto yy114;
		default:	goto yy13;
		}
yy15:
		YYDEBUG(15, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case 'l':	goto yy88;
		case 'n':	goto yy89;
		case 'x':	goto yy90;
		default:	goto yy34;
		}
yy16:
		YYDEBUG(16, *YYCURSOR);
#line 333 "forte_lexer.re"
		{ return t_id(); }
#line 448 "forte_lexer.m"
yy17:
		YYDEBUG(17, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'l':	goto yy83;
		default:	goto yy34;
		}
yy18:
		YYDEBUG(18, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'a':	goto yy77;
		default:	goto yy34;
		}
yy19:
		YYDEBUG(19, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'f':	goto yy68;
		case 'n':	goto yy70;
		default:	goto yy34;
		}
yy20:
		YYDEBUG(20, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'n':	goto yy65;
		default:	goto yy34;
		}
yy21:
		YYDEBUG(21, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'r':	goto yy63;
		default:	goto yy34;
		}
yy22:
		YYDEBUG(22, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'o':	goto yy60;
		default:	goto yy34;
		}
yy23:
		YYDEBUG(23, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(24, *YYCURSOR);
#line 321 "forte_lexer.re"
		{ return t_openparen(); }
#line 504 "forte_lexer.m"
yy25:
		YYDEBUG(25, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(26, *YYCURSOR);
#line 322 "forte_lexer.re"
		{ return t_closeparen(); }
#line 511 "forte_lexer.m"
yy27:
		YYDEBUG(27, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(28, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '"':	goto yy58;
		case '\\':	goto yy57;
		default:	goto yy27;
		}
yy29:
		YYDEBUG(29, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(30, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\'':	goto yy55;
		case '\\':	goto yy54;
		default:	goto yy29;
		}
yy31:
		YYDEBUG(31, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '=':	goto yy52;
		default:	goto yy13;
		}
yy32:
		YYDEBUG(32, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '=':	goto yy50;
		default:	goto yy13;
		}
yy33:
		YYDEBUG(33, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
yy34:
		YYDEBUG(34, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy16;
		}
yy35:
		YYDEBUG(35, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(36, *YYCURSOR);
#line 335 "forte_lexer.re"
		{ return t_dot(); }
#line 629 "forte_lexer.m"
yy37:
		YYDEBUG(37, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(38, *YYCURSOR);
#line 336 "forte_lexer.re"
		{ return t_pipe(); }
#line 636 "forte_lexer.m"
yy39:
		YYDEBUG(39, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(40, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\t':
		case ' ':	goto yy39;
		default:	goto yy41;
		}
yy41:
		YYDEBUG(41, *YYCURSOR);
#line 338 "forte_lexer.re"
		{ goto start; }
#line 652 "forte_lexer.m"
yy42:
		YYDEBUG(42, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '*':	goto yy45;
		default:	goto yy13;
		}
yy43:
		YYDEBUG(43, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(44, *YYCURSOR);
#line 351 "forte_lexer.re"
		{ [NSException raise:@"LexerException" format:@"Reached the end of file in invalid state."]; }
#line 667 "forte_lexer.m"
yy45:
		YYDEBUG(45, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(46, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '*':	goto yy47;
		default:	goto yy45;
		}
yy47:
		YYDEBUG(47, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '/':	goto yy48;
		default:	goto yy45;
		}
yy48:
		YYDEBUG(48, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(49, *YYCURSOR);
#line 339 "forte_lexer.re"
		{
        inc_line_number();
        goto start;
    }
#line 696 "forte_lexer.m"
yy50:
		YYDEBUG(50, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(51, *YYCURSOR);
#line 327 "forte_lexer.re"
		{ return t_notequal(); }
#line 703 "forte_lexer.m"
yy52:
		YYDEBUG(52, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(53, *YYCURSOR);
#line 326 "forte_lexer.re"
		{ return t_equal(); }
#line 710 "forte_lexer.m"
yy54:
		YYDEBUG(54, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\n':	goto yy13;
		default:	goto yy29;
		}
yy55:
		YYDEBUG(55, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(56, *YYCURSOR);
#line 325 "forte_lexer.re"
		{ return t_single_string(); }
#line 726 "forte_lexer.m"
yy57:
		YYDEBUG(57, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\n':	goto yy13;
		default:	goto yy27;
		}
yy58:
		YYDEBUG(58, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(59, *YYCURSOR);
#line 324 "forte_lexer.re"
		{ return t_double_string(); }
#line 742 "forte_lexer.m"
yy60:
		YYDEBUG(60, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 't':	goto yy61;
		default:	goto yy34;
		}
yy61:
		YYDEBUG(61, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy62;
		}
yy62:
		YYDEBUG(62, *YYCURSOR);
#line 319 "forte_lexer.re"
		{ return t_not(); }
#line 825 "forte_lexer.m"
yy63:
		YYDEBUG(63, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy64;
		}
yy64:
		YYDEBUG(64, *YYCURSOR);
#line 318 "forte_lexer.re"
		{ return t_or(); }
#line 900 "forte_lexer.m"
yy65:
		YYDEBUG(65, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy66;
		default:	goto yy34;
		}
yy66:
		YYDEBUG(66, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy67;
		}
yy67:
		YYDEBUG(67, *YYCURSOR);
#line 317 "forte_lexer.re"
		{ return t_and(); }
#line 983 "forte_lexer.m"
yy68:
		YYDEBUG(68, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy69;
		}
yy69:
		YYDEBUG(69, *YYCURSOR);
#line 328 "forte_lexer.re"
		{ return t_if(); }
#line 1058 "forte_lexer.m"
yy70:
		YYDEBUG(70, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'c':	goto yy71;
		default:	goto yy34;
		}
yy71:
		YYDEBUG(71, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'l':	goto yy72;
		default:	goto yy34;
		}
yy72:
		YYDEBUG(72, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'u':	goto yy73;
		default:	goto yy34;
		}
yy73:
		YYDEBUG(73, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy74;
		default:	goto yy34;
		}
yy74:
		YYDEBUG(74, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy75;
		default:	goto yy34;
		}
yy75:
		YYDEBUG(75, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy76;
		}
yy76:
		YYDEBUG(76, *YYCURSOR);
#line 315 "forte_lexer.re"
		{ return t_include(); }
#line 1173 "forte_lexer.m"
yy77:
		YYDEBUG(77, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'r':	goto yy78;
		default:	goto yy34;
		}
yy78:
		YYDEBUG(78, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy79;
		default:	goto yy34;
		}
yy79:
		YYDEBUG(79, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'n':	goto yy80;
		default:	goto yy34;
		}
yy80:
		YYDEBUG(80, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 't':	goto yy81;
		default:	goto yy34;
		}
yy81:
		YYDEBUG(81, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy82;
		}
yy82:
		YYDEBUG(82, *YYCURSOR);
#line 314 "forte_lexer.re"
		{ return t_parent(); }
#line 1280 "forte_lexer.m"
yy83:
		YYDEBUG(83, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'o':	goto yy84;
		default:	goto yy34;
		}
yy84:
		YYDEBUG(84, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'c':	goto yy85;
		default:	goto yy34;
		}
yy85:
		YYDEBUG(85, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'k':	goto yy86;
		default:	goto yy34;
		}
yy86:
		YYDEBUG(86, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy87;
		}
yy87:
		YYDEBUG(87, *YYCURSOR);
#line 312 "forte_lexer.re"
		{ return t_block(); }
#line 1379 "forte_lexer.m"
yy88:
		YYDEBUG(88, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 's':	goto yy108;
		default:	goto yy34;
		}
yy89:
		YYDEBUG(89, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy97;
		default:	goto yy34;
		}
yy90:
		YYDEBUG(90, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 't':	goto yy91;
		default:	goto yy34;
		}
yy91:
		YYDEBUG(91, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy92;
		default:	goto yy34;
		}
yy92:
		YYDEBUG(92, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'n':	goto yy93;
		default:	goto yy34;
		}
yy93:
		YYDEBUG(93, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy94;
		default:	goto yy34;
		}
yy94:
		YYDEBUG(94, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 's':	goto yy95;
		default:	goto yy34;
		}
yy95:
		YYDEBUG(95, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy96;
		}
yy96:
		YYDEBUG(96, *YYCURSOR);
#line 311 "forte_lexer.re"
		{ return t_extends(); }
#line 1510 "forte_lexer.m"
yy97:
		YYDEBUG(97, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		case 'b':	goto yy99;
		case 'i':	goto yy100;
		default:	goto yy98;
		}
yy98:
		YYDEBUG(98, *YYCURSOR);
#line 332 "forte_lexer.re"
		{ return t_end(); }
#line 1585 "forte_lexer.m"
yy99:
		YYDEBUG(99, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'l':	goto yy103;
		default:	goto yy34;
		}
yy100:
		YYDEBUG(100, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'f':	goto yy101;
		default:	goto yy34;
		}
yy101:
		YYDEBUG(101, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy102;
		}
yy102:
		YYDEBUG(102, *YYCURSOR);
#line 331 "forte_lexer.re"
		{ return t_endif(); }
#line 1676 "forte_lexer.m"
yy103:
		YYDEBUG(103, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'o':	goto yy104;
		default:	goto yy34;
		}
yy104:
		YYDEBUG(104, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'c':	goto yy105;
		default:	goto yy34;
		}
yy105:
		YYDEBUG(105, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'k':	goto yy106;
		default:	goto yy34;
		}
yy106:
		YYDEBUG(106, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy107;
		}
yy107:
		YYDEBUG(107, *YYCURSOR);
#line 313 "forte_lexer.re"
		{ return t_endblock(); }
#line 1775 "forte_lexer.m"
yy108:
		YYDEBUG(108, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy109;
		default:	goto yy34;
		}
yy109:
		YYDEBUG(109, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		case 'i':	goto yy111;
		default:	goto yy110;
		}
yy110:
		YYDEBUG(110, *YYCURSOR);
#line 330 "forte_lexer.re"
		{ return t_else(); }
#line 1858 "forte_lexer.m"
yy111:
		YYDEBUG(111, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'f':	goto yy112;
		default:	goto yy34;
		}
yy112:
		YYDEBUG(112, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy33;
		default:	goto yy113;
		}
yy113:
		YYDEBUG(113, *YYCURSOR);
#line 329 "forte_lexer.re"
		{ return t_elseif(); }
#line 1941 "forte_lexer.m"
yy114:
		YYDEBUG(114, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(115, *YYCURSOR);
		YYSETSTATE(yycRAW);
#line 306 "forte_lexer.re"
		goto start;
#line 1949 "forte_lexer.m"
/* *********************************** */
yyc_RAW:
		YYDEBUG(116, *YYCURSOR);
		yych = *(YYMARKER = YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case 0x00:	goto yy122;
		case '{':	goto yy119;
		default:	goto yy120;
		}
yy118:
		YYDEBUG(118, *YYCURSOR);
#line 308 "forte_lexer.re"
		{ return t_raw(); }
#line 1964 "forte_lexer.m"
yy119:
		YYDEBUG(119, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '#':	goto yy128;
		case '%':	goto yy130;
		case '{':	goto yy126;
		default:	goto yy120;
		}
yy120:
		YYDEBUG(120, *YYCURSOR);
		YYMARKER = ++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(121, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case 0x00:	goto yy118;
		case '{':	goto yy124;
		default:	goto yy120;
		}
yy122:
		YYDEBUG(122, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(123, *YYCURSOR);
#line 309 "forte_lexer.re"
		{ return 0; }
#line 1992 "forte_lexer.m"
yy124:
		YYDEBUG(124, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '#':
		case '%':
		case '{':	goto yy125;
		default:	goto yy120;
		}
yy125:
		YYDEBUG(125, *YYCURSOR);
		YYCURSOR = YYMARKER;
		goto yy118;
yy126:
		YYDEBUG(126, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(127, *YYCURSOR);
		YYSETSTATE(yycECHO);
#line 303 "forte_lexer.re"
		{ return t_echo(); }
#line 2015 "forte_lexer.m"
yy128:
		YYDEBUG(128, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(129, *YYCURSOR);
		YYSETSTATE(yycCOMMENT);
#line 302 "forte_lexer.re"
		goto start;
#line 2023 "forte_lexer.m"
yy130:
		YYDEBUG(130, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(131, *YYCURSOR);
		YYSETSTATE(yycSTATEMENT);
#line 301 "forte_lexer.re"
		goto start;
#line 2031 "forte_lexer.m"
/* *********************************** */
yyc_STATEMENT:
		YYDEBUG(132, *YYCURSOR);
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 0x00:	goto yy164;
		case '\t':
		case ' ':	goto yy160;
		case '!':	goto yy153;
		case '"':	goto yy148;
		case '%':	goto yy135;
		case '\'':	goto yy150;
		case '(':	goto yy144;
		case ')':	goto yy146;
		case '.':	goto yy156;
		case '/':	goto yy163;
		case '=':	goto yy152;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'c':
		case 'd':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		case 'a':	goto yy141;
		case 'b':	goto yy138;
		case 'e':	goto yy136;
		case 'i':	goto yy140;
		case 'n':	goto yy143;
		case 'o':	goto yy142;
		case 'p':	goto yy139;
		case '|':	goto yy158;
		default:	goto yy134;
		}
yy134:
		YYDEBUG(134, *YYCURSOR);
yy135:
		YYDEBUG(135, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '}':	goto yy235;
		default:	goto yy134;
		}
yy136:
		YYDEBUG(136, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case 'l':	goto yy209;
		case 'n':	goto yy210;
		case 'x':	goto yy211;
		default:	goto yy155;
		}
yy137:
		YYDEBUG(137, *YYCURSOR);
#line 333 "forte_lexer.re"
		{ return t_id(); }
#line 2130 "forte_lexer.m"
yy138:
		YYDEBUG(138, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'l':	goto yy204;
		default:	goto yy155;
		}
yy139:
		YYDEBUG(139, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'a':	goto yy198;
		default:	goto yy155;
		}
yy140:
		YYDEBUG(140, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'f':	goto yy189;
		case 'n':	goto yy191;
		default:	goto yy155;
		}
yy141:
		YYDEBUG(141, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'n':	goto yy186;
		default:	goto yy155;
		}
yy142:
		YYDEBUG(142, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'r':	goto yy184;
		default:	goto yy155;
		}
yy143:
		YYDEBUG(143, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'o':	goto yy181;
		default:	goto yy155;
		}
yy144:
		YYDEBUG(144, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(145, *YYCURSOR);
#line 321 "forte_lexer.re"
		{ return t_openparen(); }
#line 2186 "forte_lexer.m"
yy146:
		YYDEBUG(146, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(147, *YYCURSOR);
#line 322 "forte_lexer.re"
		{ return t_closeparen(); }
#line 2193 "forte_lexer.m"
yy148:
		YYDEBUG(148, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(149, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '"':	goto yy179;
		case '\\':	goto yy178;
		default:	goto yy148;
		}
yy150:
		YYDEBUG(150, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(151, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\'':	goto yy176;
		case '\\':	goto yy175;
		default:	goto yy150;
		}
yy152:
		YYDEBUG(152, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '=':	goto yy173;
		default:	goto yy134;
		}
yy153:
		YYDEBUG(153, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '=':	goto yy171;
		default:	goto yy134;
		}
yy154:
		YYDEBUG(154, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
yy155:
		YYDEBUG(155, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy137;
		}
yy156:
		YYDEBUG(156, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(157, *YYCURSOR);
#line 335 "forte_lexer.re"
		{ return t_dot(); }
#line 2311 "forte_lexer.m"
yy158:
		YYDEBUG(158, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(159, *YYCURSOR);
#line 336 "forte_lexer.re"
		{ return t_pipe(); }
#line 2318 "forte_lexer.m"
yy160:
		YYDEBUG(160, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(161, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\t':
		case ' ':	goto yy160;
		default:	goto yy162;
		}
yy162:
		YYDEBUG(162, *YYCURSOR);
#line 338 "forte_lexer.re"
		{ goto start; }
#line 2334 "forte_lexer.m"
yy163:
		YYDEBUG(163, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '*':	goto yy166;
		default:	goto yy134;
		}
yy164:
		YYDEBUG(164, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(165, *YYCURSOR);
#line 351 "forte_lexer.re"
		{ [NSException raise:@"LexerException" format:@"Reached the end of file in invalid state."]; }
#line 2349 "forte_lexer.m"
yy166:
		YYDEBUG(166, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(167, *YYCURSOR);
		YYDEBUG(-1, yych);
		switch (yych) {
		case '*':	goto yy168;
		default:	goto yy166;
		}
yy168:
		YYDEBUG(168, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '/':	goto yy169;
		default:	goto yy166;
		}
yy169:
		YYDEBUG(169, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(170, *YYCURSOR);
#line 339 "forte_lexer.re"
		{
        inc_line_number();
        goto start;
    }
#line 2378 "forte_lexer.m"
yy171:
		YYDEBUG(171, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(172, *YYCURSOR);
#line 327 "forte_lexer.re"
		{ return t_notequal(); }
#line 2385 "forte_lexer.m"
yy173:
		YYDEBUG(173, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(174, *YYCURSOR);
#line 326 "forte_lexer.re"
		{ return t_equal(); }
#line 2392 "forte_lexer.m"
yy175:
		YYDEBUG(175, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\n':	goto yy134;
		default:	goto yy150;
		}
yy176:
		YYDEBUG(176, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(177, *YYCURSOR);
#line 325 "forte_lexer.re"
		{ return t_single_string(); }
#line 2408 "forte_lexer.m"
yy178:
		YYDEBUG(178, *YYCURSOR);
		++YYCURSOR;
		yych = *YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case '\n':	goto yy134;
		default:	goto yy148;
		}
yy179:
		YYDEBUG(179, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(180, *YYCURSOR);
#line 324 "forte_lexer.re"
		{ return t_double_string(); }
#line 2424 "forte_lexer.m"
yy181:
		YYDEBUG(181, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 't':	goto yy182;
		default:	goto yy155;
		}
yy182:
		YYDEBUG(182, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy183;
		}
yy183:
		YYDEBUG(183, *YYCURSOR);
#line 319 "forte_lexer.re"
		{ return t_not(); }
#line 2507 "forte_lexer.m"
yy184:
		YYDEBUG(184, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy185;
		}
yy185:
		YYDEBUG(185, *YYCURSOR);
#line 318 "forte_lexer.re"
		{ return t_or(); }
#line 2582 "forte_lexer.m"
yy186:
		YYDEBUG(186, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy187;
		default:	goto yy155;
		}
yy187:
		YYDEBUG(187, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy188;
		}
yy188:
		YYDEBUG(188, *YYCURSOR);
#line 317 "forte_lexer.re"
		{ return t_and(); }
#line 2665 "forte_lexer.m"
yy189:
		YYDEBUG(189, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy190;
		}
yy190:
		YYDEBUG(190, *YYCURSOR);
#line 328 "forte_lexer.re"
		{ return t_if(); }
#line 2740 "forte_lexer.m"
yy191:
		YYDEBUG(191, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'c':	goto yy192;
		default:	goto yy155;
		}
yy192:
		YYDEBUG(192, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'l':	goto yy193;
		default:	goto yy155;
		}
yy193:
		YYDEBUG(193, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'u':	goto yy194;
		default:	goto yy155;
		}
yy194:
		YYDEBUG(194, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy195;
		default:	goto yy155;
		}
yy195:
		YYDEBUG(195, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy196;
		default:	goto yy155;
		}
yy196:
		YYDEBUG(196, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy197;
		}
yy197:
		YYDEBUG(197, *YYCURSOR);
#line 315 "forte_lexer.re"
		{ return t_include(); }
#line 2855 "forte_lexer.m"
yy198:
		YYDEBUG(198, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'r':	goto yy199;
		default:	goto yy155;
		}
yy199:
		YYDEBUG(199, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy200;
		default:	goto yy155;
		}
yy200:
		YYDEBUG(200, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'n':	goto yy201;
		default:	goto yy155;
		}
yy201:
		YYDEBUG(201, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 't':	goto yy202;
		default:	goto yy155;
		}
yy202:
		YYDEBUG(202, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy203;
		}
yy203:
		YYDEBUG(203, *YYCURSOR);
#line 314 "forte_lexer.re"
		{ return t_parent(); }
#line 2962 "forte_lexer.m"
yy204:
		YYDEBUG(204, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'o':	goto yy205;
		default:	goto yy155;
		}
yy205:
		YYDEBUG(205, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'c':	goto yy206;
		default:	goto yy155;
		}
yy206:
		YYDEBUG(206, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'k':	goto yy207;
		default:	goto yy155;
		}
yy207:
		YYDEBUG(207, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy208;
		}
yy208:
		YYDEBUG(208, *YYCURSOR);
#line 312 "forte_lexer.re"
		{ return t_block(); }
#line 3061 "forte_lexer.m"
yy209:
		YYDEBUG(209, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 's':	goto yy229;
		default:	goto yy155;
		}
yy210:
		YYDEBUG(210, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy218;
		default:	goto yy155;
		}
yy211:
		YYDEBUG(211, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 't':	goto yy212;
		default:	goto yy155;
		}
yy212:
		YYDEBUG(212, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy213;
		default:	goto yy155;
		}
yy213:
		YYDEBUG(213, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'n':	goto yy214;
		default:	goto yy155;
		}
yy214:
		YYDEBUG(214, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'd':	goto yy215;
		default:	goto yy155;
		}
yy215:
		YYDEBUG(215, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 's':	goto yy216;
		default:	goto yy155;
		}
yy216:
		YYDEBUG(216, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy217;
		}
yy217:
		YYDEBUG(217, *YYCURSOR);
#line 311 "forte_lexer.re"
		{ return t_extends(); }
#line 3192 "forte_lexer.m"
yy218:
		YYDEBUG(218, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		case 'b':	goto yy220;
		case 'i':	goto yy221;
		default:	goto yy219;
		}
yy219:
		YYDEBUG(219, *YYCURSOR);
#line 332 "forte_lexer.re"
		{ return t_end(); }
#line 3267 "forte_lexer.m"
yy220:
		YYDEBUG(220, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'l':	goto yy224;
		default:	goto yy155;
		}
yy221:
		YYDEBUG(221, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'f':	goto yy222;
		default:	goto yy155;
		}
yy222:
		YYDEBUG(222, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy223;
		}
yy223:
		YYDEBUG(223, *YYCURSOR);
#line 331 "forte_lexer.re"
		{ return t_endif(); }
#line 3358 "forte_lexer.m"
yy224:
		YYDEBUG(224, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'o':	goto yy225;
		default:	goto yy155;
		}
yy225:
		YYDEBUG(225, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'c':	goto yy226;
		default:	goto yy155;
		}
yy226:
		YYDEBUG(226, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'k':	goto yy227;
		default:	goto yy155;
		}
yy227:
		YYDEBUG(227, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy228;
		}
yy228:
		YYDEBUG(228, *YYCURSOR);
#line 313 "forte_lexer.re"
		{ return t_endblock(); }
#line 3457 "forte_lexer.m"
yy229:
		YYDEBUG(229, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'e':	goto yy230;
		default:	goto yy155;
		}
yy230:
		YYDEBUG(230, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		case 'i':	goto yy232;
		default:	goto yy231;
		}
yy231:
		YYDEBUG(231, *YYCURSOR);
#line 330 "forte_lexer.re"
		{ return t_else(); }
#line 3540 "forte_lexer.m"
yy232:
		YYDEBUG(232, *YYCURSOR);
		yych = *++YYCURSOR;
		YYDEBUG(-1, yych);
		switch (yych) {
		case 'f':	goto yy233;
		default:	goto yy155;
		}
yy233:
		YYDEBUG(233, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(-1, yych);
		switch ((yych = *YYCURSOR)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy154;
		default:	goto yy234;
		}
yy234:
		YYDEBUG(234, *YYCURSOR);
#line 329 "forte_lexer.re"
		{ return t_elseif(); }
#line 3623 "forte_lexer.m"
yy235:
		YYDEBUG(235, *YYCURSOR);
		++YYCURSOR;
		YYDEBUG(236, *YYCURSOR);
		YYSETSTATE(yycRAW);
#line 304 "forte_lexer.re"
		goto start;
#line 3631 "forte_lexer.m"
	}
#line 352 "forte_lexer.re"

}

